/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerEmergencyRouteImport } from './routes/owner.emergency'
import { Route as OwnerIntakeRouteImport } from './routes/owner.intake'
import { Route as OwnerProductsRouteImport } from './routes/owner.products'
import { Route as ShelterContactRouteImport } from './routes/shelter.contact'
import { Route as ShelterEventsRouteImport } from './routes/shelter.events'
import { Route as ShelterGalleryRouteImport } from './routes/shelter.gallery'
import { Route as ShelterStoriesRouteImport } from './routes/shelter.stories'
import { Route as VetDashboardRouteImport } from './routes/vet.dashboard'
import { Route as VetIntakeRouteImport } from './routes/vet.intake'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerEmergencyRoute = OwnerEmergencyRouteImport.update({
  id: '/owner/emergency',
  path: '/owner/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIntakeRoute = OwnerIntakeRouteImport.update({
  id: '/owner/intake',
  path: '/owner/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/owner/products',
  path: '/owner/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterContactRoute = ShelterContactRouteImport.update({
  id: '/shelter/contact',
  path: '/shelter/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterEventsRoute = ShelterEventsRouteImport.update({
  id: '/shelter/events',
  path: '/shelter/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterGalleryRoute = ShelterGalleryRouteImport.update({
  id: '/shelter/gallery',
  path: '/shelter/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterStoriesRoute = ShelterStoriesRouteImport.update({
  id: '/shelter/stories',
  path: '/shelter/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VetDashboardRoute = VetDashboardRouteImport.update({
  id: '/vet/dashboard',
  path: '/vet/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VetIntakeRoute = VetIntakeRouteImport.update({
  id: '/vet/intake',
  path: '/vet/intake',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/emergency': typeof OwnerEmergencyRoute
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/products': typeof OwnerProductsRoute
  '/shelter/contact': typeof ShelterContactRoute
  '/shelter/events': typeof ShelterEventsRoute
  '/shelter/gallery': typeof ShelterGalleryRoute
  '/shelter/stories': typeof ShelterStoriesRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/intake': typeof VetIntakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/emergency': typeof OwnerEmergencyRoute
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/products': typeof OwnerProductsRoute
  '/shelter/contact': typeof ShelterContactRoute
  '/shelter/events': typeof ShelterEventsRoute
  '/shelter/gallery': typeof ShelterGalleryRoute
  '/shelter/stories': typeof ShelterStoriesRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/intake': typeof VetIntakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/feedback': typeof FeedbackRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/emergency': typeof OwnerEmergencyRoute
  '/owner/intake': typeof OwnerIntakeRoute
  '/owner/products': typeof OwnerProductsRoute
  '/shelter/contact': typeof ShelterContactRoute
  '/shelter/events': typeof ShelterEventsRoute
  '/shelter/gallery': typeof ShelterGalleryRoute
  '/shelter/stories': typeof ShelterStoriesRoute
  '/vet/dashboard': typeof VetDashboardRoute
  '/vet/intake': typeof VetIntakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/feedback'
    | '/owner/dashboard'
    | '/owner/emergency'
    | '/owner/intake'
    | '/owner/products'
    | '/shelter/contact'
    | '/shelter/events'
    | '/shelter/gallery'
    | '/shelter/stories'
    | '/vet/dashboard'
    | '/vet/intake'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/feedback'
    | '/owner/dashboard'
    | '/owner/emergency'
    | '/owner/intake'
    | '/owner/products'
    | '/shelter/contact'
    | '/shelter/events'
    | '/shelter/gallery'
    | '/shelter/stories'
    | '/vet/dashboard'
    | '/vet/intake'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/feedback'
    | '/owner/dashboard'
    | '/owner/emergency'
    | '/owner/intake'
    | '/owner/products'
    | '/shelter/contact'
    | '/shelter/events'
    | '/shelter/gallery'
    | '/shelter/stories'
    | '/vet/dashboard'
    | '/vet/intake'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeedbackRoute: typeof FeedbackRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerEmergencyRoute: typeof OwnerEmergencyRoute
  OwnerIntakeRoute: typeof OwnerIntakeRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  ShelterContactRoute: typeof ShelterContactRoute
  ShelterEventsRoute: typeof ShelterEventsRoute
  ShelterGalleryRoute: typeof ShelterGalleryRoute
  ShelterStoriesRoute: typeof ShelterStoriesRoute
  VetDashboardRoute: typeof VetDashboardRoute
  VetIntakeRoute: typeof VetIntakeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/emergency': {
      id: '/owner/emergency'
      path: '/owner/emergency'
      fullPath: '/owner/emergency'
      preLoaderRoute: typeof OwnerEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/intake': {
      id: '/owner/intake'
      path: '/owner/intake'
      fullPath: '/owner/intake'
      preLoaderRoute: typeof OwnerIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/products': {
      id: '/owner/products'
      path: '/owner/products'
      fullPath: '/owner/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter/contact': {
      id: '/shelter/contact'
      path: '/shelter/contact'
      fullPath: '/shelter/contact'
      preLoaderRoute: typeof ShelterContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter/events': {
      id: '/shelter/events'
      path: '/shelter/events'
      fullPath: '/shelter/events'
      preLoaderRoute: typeof ShelterEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter/gallery': {
      id: '/shelter/gallery'
      path: '/shelter/gallery'
      fullPath: '/shelter/gallery'
      preLoaderRoute: typeof ShelterGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter/stories': {
      id: '/shelter/stories'
      path: '/shelter/stories'
      fullPath: '/shelter/stories'
      preLoaderRoute: typeof ShelterStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/dashboard': {
      id: '/vet/dashboard'
      path: '/vet/dashboard'
      fullPath: '/vet/dashboard'
      preLoaderRoute: typeof VetDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet/intake': {
      id: '/vet/intake'
      path: '/vet/intake'
      fullPath: '/vet/intake'
      preLoaderRoute: typeof VetIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeedbackRoute: FeedbackRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerEmergencyRoute: OwnerEmergencyRoute,
  OwnerIntakeRoute: OwnerIntakeRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  ShelterContactRoute: ShelterContactRoute,
  ShelterEventsRoute: ShelterEventsRoute,
  ShelterGalleryRoute: ShelterGalleryRoute,
  ShelterStoriesRoute: ShelterStoriesRoute,
  VetDashboardRoute: VetDashboardRoute,
  VetIntakeRoute: VetIntakeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
